In [1]:
import numpy as np

import keras

from keras.models import Sequential

from keras.layers import Dense, Dropout, Flatten

from keras.layers import Conv2D, MaxPooling2D

from tensorflow.keras.optimizers import SGD


x_train = np.random.random((100, 100, 100, 3))

y_train = keras.utils.np_utils.to_categorical(
np.random.randint(10, size=(100, 1)), num_classes=10)

x_test = np.random.random((20, 100, 100, 3))

y_test = keras.utils.np_utils.to_categorical(
np.random.randint(10, size=(20, 1)), num_classes=10)

model = Sequential()

model.add(Conv2D(32, (3, 3), activation='relu',
input_shape=(100, 100, 3)))

model.add(Conv2D(32, (3, 3), activation='relu'))

model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), activation='relu'))

model.add(Conv2D(64, (3, 3), activation='relu'))

model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.25))

model.add(Flatten())

model.add(Dense(256, activation='relu'))

model.add(Dropout(0.5))

model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

model.compile(loss='categorical_crossentropy', optimizer=sgd)

# model.fit(x_train, y_train, batch_size=32, epochs=10)

print(
    # model.predict(
np.random.random((100, 100, 100, 3))
# )
)



[[[[2.49054154e-01 9.98807971e-01 6.05016421e-01]
   [6.34219126e-01 6.07431686e-02 1.53140439e-01]
   [8.99924368e-02 3.29615899e-01 6.79806254e-01]
   ...
   [6.89245247e-01 7.40831255e-01 6.30934637e-01]
   [6.71737653e-01 5.79108572e-01 2.87618888e-02]
   [9.47468023e-01 5.60758484e-01 8.55509732e-01]]

  [[9.90357184e-01 2.30080499e-01 2.68990771e-02]
   [3.82703876e-01 2.83326790e-02 5.52300096e-01]
   [6.99392502e-01 4.93745933e-01 9.92729674e-02]
   ...
   [6.33226600e-01 5.87184727e-01 7.44925400e-01]
   [8.68368638e-01 8.99119984e-01 7.80145961e-01]
   [9.69041096e-01 4.19623423e-01 7.27175174e-01]]

  [[9.75107655e-01 5.07109001e-01 1.28373954e-01]
   [4.00435470e-01 7.55889037e-01 4.31112134e-02]
   [1.05222040e-01 6.72400153e-01 4.97889742e-01]
   ...
   [3.11226307e-01 5.08500012e-01 9.47492528e-01]
   [2.75980031e-01 6.09684447e-01 5.43204676e-01]
   [4.50419732e-01 7.90976305e-01 7.69188416e-01]]

  ...

  [[3.65464428e-03 9.76719262e-01 3.37615962e-01]
   [9.16823192e-

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)
